info:
  app:
    name: Crewlance Server API

server:
  port: 9001

spring:

  datasource:
    url: jdbc:mysql://localhost/crewlance
    username: root
    password: password
    initialization-mode: always

  jpa:
    show-sql: true
    generate-ddl: false

    hibernate:
      ddl-auto: none

    properties:
      javax:
        persistence:
          validation:
            mode: none

graphql:

  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

  tools:
    schemaLocationPattern: "**/graphql_schema/*.graphqls"