package com.crewlance.server.service;

import com.crewlance.server.error.ResourceNotFoundException;
import com.crewlance.server.model.Project;
import com.crewlance.server.model.ProjectKeyword;
import com.crewlance.server.repository.ProjectRepository;
import com.crewlance.server.scheduler.ProjectScheduler;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

import static com.crewlance.server.model.QProject.project;
import static org.jooq.lambda.Seq.seq;

@Service
public class ProjectService extends BaseService {

    private final ProjectRepository projectRepository;
    private final ProjectScheduler projectScheduler;

    public ProjectService(ProjectRepository projectRepository, ProjectScheduler projectScheduler) {
        this.projectRepository = projectRepository;
        this.projectScheduler = projectScheduler;
    }

    @Transactional
    public Project create(Project project) {
        generateKeywords(project);
        return projectRepository.save(project);
    }

    @Transactional
    public Project update(Project project) {
        removeGeneratedKeywords(project);
        generateKeywords(project);
        return projectRepository.save(project);
    }

    @Transactional
    public Project schedule(Project project) {
        projectScheduler.scheduleProject(project);
        return projectRepository.save(project);
    }

    @Transactional
    public String delete(Project project) {
        projectRepository.delete(project);
        return project.getId();
    }

    public List<Project> findAll() {
        return seq(projectRepository.findAll(project.start.asc(), project.end.asc())).toList();
    }

    public Project findById(String id) {
        return projectRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException(String.format("Could not find project with id: %s", id)));
    }

    private static void removeGeneratedKeywords(Project project) {
        project.getKeywords().removeAll(seq(project.getKeywords())
                .filter(keyword -> keyword.isAutoGenerated())
                .toSet());
    }

    private static void generateKeywords(Project project) {
        project.getKeywords().add(new ProjectKeyword(project, project.getLocation(), true));
    }
}
