package com.crewlance.server.model;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Type;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
@Getter
@Setter
public class ProjectKeyword extends DomainObject {

    private static final long serialVersionUID = -4825508730943963083L;

    @Column(length = 100, nullable = false)
    private String value;

    @Column(length = 250)
    private String notes;

    @Column(nullable = false)
    @Type(type= "org.hibernate.type.NumericBooleanType")
    private boolean autoGenerated;

    @ManyToOne(optional = false)
    private Project project;

    public ProjectKeyword() {
    }

    public ProjectKeyword(Project project, String value, String notes) {
        this.project = project;
        this.value = value;
        this.notes = notes;
        this.autoGenerated = false;
    }

    public ProjectKeyword(Project project, String value, boolean autoGenerated) {
        this.project = project;
        this.value = value;
        this.notes = autoGenerated ? "This keyword was auto-generated." : null;
        this.autoGenerated = autoGenerated;
    }
}
